name: VideoTVA

on:
  schedule:
    - cron: '0 */3 * * *'  # Run every 6 hours
  workflow_dispatch:

env:
  USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  REFERER: "https://www.livehdtv.net"
  PYTHON_VERSION: '3.x'

jobs:
  generate_m3u8:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create directories
        run: mkdir -p txt fr

      - name: Generate Simple M3U Playlists
        run: |
          channels=("videotva" "videoqub" "videolci")
          for channel in "${channels[@]}"; do
            python_output=$(python py/$channel.py)
            echo "#EXTM3U" > fr/$channel.m3u
            echo "#EXTINF:-1, ${channel^}" >> fr/$channel.m3u
            echo "$python_output" >> fr/$channel.m3u
            [[ $channel == "videotva" ]] && echo "$python_output" > txt/$channel.txt
          done

      - name: Generate M3U8 Playlists
        run: |
          channels=("m6" "w9" "6ter" "artvfr" "cstar")
          for channel in "${channels[@]}"; do
            python_output=$(python py/video$channel.py)
            curl_output=$(curl -s -e "$REFERER" -A "$USER_AGENT" "$python_output")
            echo "$curl_output" | sed "s|tracks-|https://livetvde.net/$channel/tracks-|g" > fr/video$channel.m3u8
          done

      - name: Validate Generated Files
        run: |
          echo "Generated files:"
          ls -la fr/
          echo "File sizes:"
          du -h fr/*

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update TV playlists"
          branch: main
          file_pattern: |
            fr/*.m3u
            fr/*.m3u8
            txt/*.txt
        env:
          GITHUB_TOKEN: ${{ secrets.ROTANA_TOKEN }}
