name: Run Script Every 3 Hours FR

on:
  schedule:
    - cron: '0 */3 * * *'  # Toutes les 3 heures
  workflow_dispatch:        # Déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create Required Folders
        run: mkdir -p fr txt ar py

      - name: Run Script and Generate M3U8 for VideoTiji
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/6-M6/6-M6.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videotiji.m3u8
          else
            echo "Erreur: URL source non trouvée pour TF1"
          fi
          
      - name: Run Script and Generate M3U8 for VideoTF1
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/1-TF1/1-TF1.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videotf1.m3u8
          else
            echo "Erreur: URL source non trouvée pour TF1"
          fi

      - name: Run Script and Generate M3U8 for VideoTF1FS
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/20-TF1SERIESFILMS/20-TF1SERIESFILMS.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videotf1fs.m3u8
          else
            echo "Erreur: URL source non trouvée pour TF1SERIESFILMS"
          fi

      - name: Run Script and Generate M3U8 for VideoTMC
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/10-TMC/10-TMC.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videotmc.m3u8
          else
            echo "Erreur: URL source non trouvée pour TMC"
          fi

      - name: Run Script and Generate M3U8 for VideoTFX
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/11-TFX/11-TFX.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videotfx.m3u8
          else
            echo "Erreur: URL source non trouvée pour TFX"
          fi

      - name: Run Script and Generate M3U8 for VideoCP
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/75-CANALPLUS/75-CANALPLUS.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videocp.m3u8
          else
            echo "Erreur: URL source non trouvée pour CANALPLUS"
          fi

      - name: Run Script and Generate M3U8 for VideoW9
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/9-W9/9-W9.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videow9.m3u8
          else
            echo "Erreur: URL source non trouvée pour W9"
          fi

      - name: Run Script and Generate M3U8 for Video6ter
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/22-6ter/22-6ter.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/video6ter.m3u8
          else
            echo "Erreur: URL source non trouvée pour 6ter"
          fi

      - name: Run Script and Generate M3U8 for F2
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/2-france.2/2-france.2.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videof2.m3u8
          else
            echo "Erreur: URL source non trouvée pour France 2"
          fi

      - name: Run Script and Generate M3U8 for F3
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/3-france.3/3-france.3.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videof3.m3u8
          else
            echo "Erreur: URL source non trouvée pour France 3"
          fi

      - name: Run Script and Generate M3U8 for F4
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/4-france.4/4-france.4.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videof4.m3u8
          else
            echo "Erreur: URL source non trouvée pour France 4"
          fi

      - name: Run Script and Generate M3U8 for F5
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/5-france.5/5-france.5.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videof5.m3u8
          else
            echo "Erreur: URL source non trouvée pour France 5"
          fi

      - name: Run Script and Generate M3U8 for M6
        run: |
          curl_output=$(curl -k -s -H "User-Agent: Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" "https://callofliberty.fr/tv/6-M6/6-M6.php" | grep -oP "source:\s*'\K[^']+(?=',)")
          if [ -n "$curl_output" ]; then
            curl -k -e "https://callofliberty.fr/" -A "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36" -H "Origin: https://callofliberty.fr" "$curl_output" > fr/videom6.m3u8
          else
            echo "Erreur: URL source non trouvée pour M6"
          fi

      - name: Run Script and Generate M3U8 for CTurk
        run: |
          if [ -f "py/videocnnturk.py" ]; then
            python_output=$(python py/videocnnturk.py)
            echo "#EXTM3U" > ar/videocnnturk.m3u
            echo "#EXTINF:-1, CNN Turk" >> ar/videocnnturk.m3u
            echo "$python_output" >> ar/videocnnturk.m3u
          else
            echo "Fichier py/videocnnturk.py non trouvé"
          fi

      - name: Pull changes from remote
        run: git pull origin main

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "hello@github.com"
          git config --local user.name "hello"
          git add fr/ ar/
          git diff --staged --quiet || git commit -m "Update M3U8 files - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
