name: Run Script Every 3 Hours FR

on:
  schedule:
    - cron: '0 */3 * * *'  # Toutes les 3 heures
  workflow_dispatch:        # Déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests

      - name: Create Required Folders
        run: mkdir -p fr txt ar py

      - name: Generate M3U8 for VideoTiji
        run: |
          python extract_tiji.py

      # ... autres étapes pour les autres chaînes

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "hello@github.com"
          git config --local user.name "hello"
          git add fr/ ar/
          git diff --staged --quiet || git commit -m "Update M3U8 files - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
